name: idempiere_rest
description: A useful dart client to facilitate the consume idempiere rest API
version: 1.0.2
repository: https://github.com/devcoffee/idempiere_rest

environment:
  sdk: ">=2.18.0 <3.19.0"

dependencies: 
  http: ^1.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
